version: '3.7'
name: 'constructum'

services:
  redis-test:
    image: redis:latest
    restart: always
    container_name: redis-test
    ports:
      - 6380:6380
    networks:
      cnetwork:
        ipv4_address: 77.5.0.10

  auth-test:
    image: constructum-auth:latest
    restart: always
    container_name: auth-test
    depends_on:
      - redis-test
      - identify-test
    environment:
      PORT: 11198
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27017/ctor-test?authMechanism=DEFAULT&authSource=admin
      VERIFICATION_ATTEMPTS_OF_PING_TRPC: 10
      IDENTIFY_ADDRESS: http://identify-test:9375
    networks:
      cnetwork:
        ipv4_address: 77.5.0.30
    ports:
      - 11198:11198

  api-test:
    image: constructum-api:latest
    restart: always
    container_name: api-test
    environment:
      PORT: 12221
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27017/ctor-test?authMechanism=DEFAULT&authSource=admin
      COMPILER_TRPC_ADDRESS: http://compiler-test:12246
    depends_on:
      - redis-test
      - compiler-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.40
    ports:
      - 12221:12221

  compiler-test:
    image: constructum-compiler:latest
    restart: always
    container_name: compiler-test
    environment:
      PORT: 12246
      NODE_ENV: production
    depends_on:
      - auth-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.50
    ports:
      - 12246:12245

  identify-test:
    image: constructum-identify:latest
    restart: always
    container_name: identify-test
    environment:
      PORT: 9375
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27017/ctor-test?authMechanism=DEFAULT&authSource=admin
    ports:
      - 9375:9375
    networks:
      cnetwork:
        ipv4_address: 77.5.0.60

  web-server-test:
    image: constructum-client:latest
    restart: always
    container_name: web-server-test
    depends_on:
      - api-test
      - auth-test
    ports:
      - 3593:3593
    # volumes:
    #   - './nginx/test/nginx.conf://etc/nginx/nginx.conf:ro'
    #   - './services/service.client://usr/share/nginx/html:ro'
    networks:
      cnetwork:
        ipv4_address: 77.5.0.90

networks:
  cnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 77.5.0.0/16
          gateway: 77.5.0.1
