version: '3.7'
name: 'constructum'

services:
  redis-test:
    image: redis:latest
    restart: always
    container_name: redis-test
    ports:
      - 6380:6379
    networks:
      cnetwork:
        ipv4_address: 77.5.0.10

  mongo-test:
    image: mongo:latest
    restart: always
    container_name: mongo-test
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: J_Lbdysq_Yjdsq_Vbh1
      MONGO_INITDB_DATABASE: ctor-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.20
    volumes:
      - mongodb:/data/db

  auth-test:
    image: constructum-auth:latest
    restart: always
    container_name: auth-test
    depends_on:
      - mongo-test
      - redis-test
      - identify-test
    environment:
      PORT: 11197
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@mongo-test:27017/ctor-test?authMechanism=DEFAULT&authSource=admin
      VERIFICATION_ATTEMPTS_OF_PING_TRPC: 10
      IDENTIFY_ADDRESS: http://identify:3498
    networks:
      cnetwork:
        ipv4_address: 77.5.0.30
    ports:
      - 11197:11197

  api-test:
    image: constructum-api:latest
    restart: always
    container_name: api-test
    environment:
      PORT: 7161
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@mongo-test:27017/ctor?authMechanism=DEFAULT&authSource=admin
      COMPILER_TRPC_ADDRESS: http://compiler:12245
    depends_on:
      - mongo-test
      - redis-test
      - compiler-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.40
    ports:
      - 7161:7161

  compiler-test:
    image: constructum-compiler:latest
    restart: always
    container_name: compiler-test
    environment:
      PORT: 12245
      NODE_ENV: production
    depends_on:
      - auth-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.50
    ports:
      - 12245:12245

  identify-test:
    image: constructum-identify:latest
    restart: always
    container_name: identify-test
    environment:
      PORT: 3498
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@mongo-test:27017/?authMechanism=DEFAULT&authSource=admin
    ports:
      - 3498:3498
    depends_on:
      - mongo-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.60

  web-server-test:
    image: constructum-client:latest
    restart: always
    container_name: web-server-test
    depends_on:
      - api-test
      - auth-test
    ports:
      - 8077:8077
    volumes:
      - './nginx/nginx.conf://etc/nginx/nginx.conf:ro'
      - './services/service.client://usr/share/nginx/html:ro'
    networks:
      cnetwork:
        ipv4_address: 77.5.0.90

volumes:
  mongodb:

networks:
  cnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 77.5.0.0/16
          gateway: 77.5.0.1
