version: '3.7'
name: 'constructum'

services:
  mongo-test:
    image: mongo:latest
    restart: always
    container_name: mongo-test
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: J_Lbdysq_Yjdsq_Vbh1
      MONGO_INITDB_DATABASE: ctor
    networks:
      cnetwork:
        ipv4_address: 77.5.0.20
    volumes:
      - mongodb:/data/db

  redis-test:
    image: redis:latest
    restart: always
    container_name: redis-test
    ports:
      - 6380:6380
    networks:
      cnetwork:
        ipv4_address: 77.5.0.10

  auth-test:
    image: constructum-auth:latest
    restart: always
    container_name: auth-test
    depends_on:
      - redis-test
      - identify-test
    environment:
      PORT: 11198
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27018/ctor-test?authMechanism=DEFAULT&authSource=admin
      VERIFICATION_ATTEMPTS_OF_PING_TRPC: 10
      IDENTIFY_ADDRESS: http://identify-test:9375
    networks:
      cnetwork:
        ipv4_address: 77.5.0.30
    ports:
      - 11198:11198

  api-test:
    image: constructum-api:latest
    restart: always
    container_name: api-test
    environment:
      PORT: 12221
      ENABLED_CORS: false
      REDIS_URL: redis://redis-test
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27018/ctor-test?authMechanism=DEFAULT&authSource=admin
      COMPILER_TRPC_ADDRESS: http://compiler-test:12246
    depends_on:
      - redis-test
      - compiler-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.40
    ports:
      - 12221:12221

  compiler-test:
    image: constructum-compiler:latest
    restart: always
    container_name: compiler-test
    environment:
      PORT: 12246
      NODE_ENV: production
    depends_on:
      - auth-test
    networks:
      cnetwork:
        ipv4_address: 77.5.0.50
    ports:
      - 12246:12245

  identify-test:
    image: constructum-identify:latest
    restart: always
    container_name: identify-test
    depends_on:
      - mongo-test
    environment:
      PORT: 9375
      MONGO_CONNECTION: mongodb://admin:J_Lbdysq_Yjdsq_Vbh1@45.12.74.222:27018/ctor-test?authMechanism=DEFAULT&authSource=admin
    ports:
      - 9375:9375
    networks:
      cnetwork:
        ipv4_address: 77.5.0.60

  # client-test:
  #   image: constructum-client:latest
  #   restart: always
  #   container_name: client-test
  #   ports:
  #     - 45.12.74.222:80:80
  #   volumes:
  #     #   - './services/service.client/nginx.conf://etc/nginx/nginx.conf:ro'
  #     - './services/service.client://usr/share/nginx/html:ro'
  #   networks:
  #     cnetwork:
  #       ipv4_address: 77.5.0.90

  gateway-test:
    image: ctor-gateway-test:latest
    restart: always
    container_name: gateway-test
    depends_on:
      - api-test
      - auth-test
    # volumes:
    #   - './gateway/nginx.conf://etc/nginx/nginx.conf:ro'
    ports:
      - 45.130.43.67:8033:8033
    networks:
      cnetwork:
        ipv4_address: 77.5.1.10

volumes:
  mongodb:

networks:
  cnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 77.5.0.0/16
          gateway: 77.5.0.1
