export { Login } from './page.login/Login'
export { Registration } from './page.registration/Registration'
export { Account } from './page.account/Account'
export { ViewProject } from './page.view-project/ViewProject'
export { AddEntity } from './page.add-entity/AddEntity'
export { AddProject } from './page.add-project/AddProject'
export { EntityConstructor } from './page.entity-constructor/EntityConstructor'
export { Accounts } from './page.accounts/Accounts'
